import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

type Localized<T>={fa?:Partial<T>;ps?:Partial<T>}
export type StorySettingsText={heading:string;intro:string}
export type StorySettingsInput=StorySettingsText&{translations?:Localized<StorySettingsText>}
export type StoryItemText={step:string;title:string;text:string}
export type StoryItemInput=StoryItemText&{id:string;visible:boolean;sortOrder:number;translations?:Localized<StoryItemText>}
export type StoryItemRecord=StoryItemInput&{createdAt:string;updatedAt:string}
export type LeadershipText={name:string;role:string;text:string}
export type LeadershipInput=LeadershipText&{id:string;photo:string;visible:boolean;sortOrder:number;translations?:Localized<LeadershipText>}
export type LeadershipRecord=LeadershipInput&{createdAt:string;updatedAt:string}
export type AboutData={story:StorySettingsInput&{items:StoryItemRecord[]};leaders:LeadershipRecord[]}
type StoredAboutData=AboutData
const moduleDir=path.dirname(fileURLToPath(import.meta.url)),defaultDataFile=path.join(moduleDir,'data','about.json'),clean=(v:unknown)=>typeof v==='string'?v.trim():''
const cleanId=(v:unknown,label:string)=>{const id=clean(v).toLowerCase();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id))throw new Error(`Enter a valid ${label} id using lowercase letters, numbers and hyphens.`);return id}
const emptyData=():StoredAboutData=>({story:{heading:'',intro:'',translations:{},items:[]},leaders:[]})
function tStory(v:any){const o:Partial<StorySettingsText>={};for(const k of ['heading','intro'] as const){const x=clean(v?.[k]);if(x)(o as any)[k]=x}return o}
function tItem(v:any){const o:Partial<StoryItemText>={};for(const k of ['step','title','text'] as const){const x=clean(v?.[k]);if(x)(o as any)[k]=x}return o}
function tLeader(v:any){const o:Partial<LeadershipText>={};for(const k of ['name','role','text'] as const){const x=clean(v?.[k]);if(x)(o as any)[k]=x}return o}
function normalizeStorySettings(input:StorySettingsInput):StorySettingsInput{const heading=clean(input.heading),intro=clean(input.intro);if(!heading)throw new Error('Story heading is required.');if(!intro)throw new Error('Story introduction is required.');return{heading,intro,translations:{fa:tStory(input.translations?.fa),ps:tStory(input.translations?.ps)}}}
function normalizeStoryItem(input:StoryItemInput):StoryItemInput{const id=cleanId(input.id,'story'),step=clean(input.step),title=clean(input.title),text=clean(input.text);if(!step)throw new Error('Story step is required.');if(!title)throw new Error('Story title is required.');if(!text)throw new Error('Story text is required.');return{id,step,title,text,visible:input.visible!==false,sortOrder:Number.isFinite(Number(input.sortOrder))?Number(input.sortOrder):0,translations:{fa:tItem(input.translations?.fa),ps:tItem(input.translations?.ps)}}}
function normalizeLeader(input:LeadershipInput):LeadershipInput{const id=cleanId(input.id,'leader'),name=clean(input.name),role=clean(input.role),text=clean(input.text),photo=clean(input.photo);if(!name)throw new Error('Leader name is required.');if(!role)throw new Error('Leader role is required.');if(!text)throw new Error('Leader description is required.');if(!photo)throw new Error('Leader photo is required.');return{id,name,role,text,photo,visible:input.visible!==false,sortOrder:Number.isFinite(Number(input.sortOrder))?Number(input.sortOrder):0,translations:{fa:tLeader(input.translations?.fa),ps:tLeader(input.translations?.ps)}}}
async function read(file:string):Promise<StoredAboutData>{try{const raw=JSON.parse(await readFile(file,'utf8')) as any,now=new Date().toISOString();const story=raw.story?.heading&&raw.story?.intro?normalizeStorySettings(raw.story):{heading:'',intro:'',translations:{}};const items=Array.isArray(raw.story?.items)?raw.story.items.map((x:any)=>({...normalizeStoryItem(x),createdAt:clean(x.createdAt)||now,updatedAt:clean(x.updatedAt)||now})):[];const leaders=Array.isArray(raw.leaders)?raw.leaders.map((x:any)=>({...normalizeLeader(x),createdAt:clean(x.createdAt)||now,updatedAt:clean(x.updatedAt)||now})):[];return{story:{...story,items},leaders}}catch(e:any){if(e?.code==='ENOENT')return emptyData();throw e}}
async function write(file:string,data:StoredAboutData){await mkdir(path.dirname(file),{recursive:true});const t=`${file}.tmp`;await writeFile(t,JSON.stringify(data,null,2)+'\n','utf8');await rename(t,file)}
export function createAboutStore(file=defaultDataFile){return{async getAbout(o:{includeHidden?:boolean}={}){const d=await read(file);return{story:{heading:d.story.heading,intro:d.story.intro,translations:d.story.translations,items:d.story.items.filter(x=>o.includeHidden||x.visible).sort((a,b)=>a.sortOrder-b.sortOrder||a.step.localeCompare(b.step))},leaders:d.leaders.filter(x=>o.includeHidden||x.visible).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name))}},async updateStorySettings(input:StorySettingsInput){const d=await read(file);d.story={...d.story,...normalizeStorySettings(input)};await write(file,d);return{heading:d.story.heading,intro:d.story.intro,translations:d.story.translations}},async createStoryItem(input:StoryItemInput){const n=normalizeStoryItem(input),d=await read(file);if(d.story.items.some(x=>x.id===n.id))throw new Error('A story item with this id already exists.');const now=new Date().toISOString(),x={...n,createdAt:now,updatedAt:now};d.story.items.push(x);await write(file,d);return x},async updateStoryItem(id:string,input:StoryItemInput){const d=await read(file),i=d.story.items.findIndex(x=>x.id===id);if(i<0)return null;const n=normalizeStoryItem({...input,id}),x={...d.story.items[i],...n,id,createdAt:d.story.items[i].createdAt,updatedAt:new Date().toISOString()};d.story.items[i]=x;await write(file,d);return x},async deleteStoryItem(id:string){const d=await read(file),n=d.story.items.filter(x=>x.id!==id);if(n.length===d.story.items.length)return false;d.story.items=n;await write(file,d);return true},async createLeader(input:LeadershipInput){const n=normalizeLeader(input),d=await read(file);if(d.leaders.some(x=>x.id===n.id))throw new Error('A leader with this id already exists.');const now=new Date().toISOString(),x={...n,createdAt:now,updatedAt:now};d.leaders.push(x);await write(file,d);return x},async updateLeader(id:string,input:LeadershipInput){const d=await read(file),i=d.leaders.findIndex(x=>x.id===id);if(i<0)return null;const n=normalizeLeader({...input,id}),x={...d.leaders[i],...n,id,createdAt:d.leaders[i].createdAt,updatedAt:new Date().toISOString()};d.leaders[i]=x;await write(file,d);return x},async deleteLeader(id:string){const d=await read(file),n=d.leaders.filter(x=>x.id!==id);if(n.length===d.leaders.length)return false;d.leaders=n;await write(file,d);return true}}}
const s=createAboutStore();export const getAbout=s.getAbout;export const updateStorySettings=s.updateStorySettings;export const createStoryItem=s.createStoryItem;export const updateStoryItem=s.updateStoryItem;export const deleteStoryItem=s.deleteStoryItem;export const createLeader=s.createLeader;export const updateLeader=s.updateLeader;export const deleteLeader=s.deleteLeader
