import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
type Localized<T>={fa?:Partial<T>;ps?:Partial<T>}
export type ContactDivisionText={label:string;title:string;text:string}
export type ContactDivision=ContactDivisionText&{id:string;visible:boolean;sortOrder:number;translations?:Localized<ContactDivisionText>}
export type ContactTextFields={heroKicker:string;heroTitle:string;heroHighlight:string;heroText:string;office:string;workingHours:string;infoTitle:string;infoText:string;mapTitle:string;mapText:string}
export type ContactSettings=ContactTextFields&{phone:string;email:string;whatsapp:string;mapEmbedUrl:string;divisions:ContactDivision[];translations?:Localized<ContactTextFields>}
const moduleDir=path.dirname(fileURLToPath(import.meta.url)),defaultFile=path.join(moduleDir,'data','contact.json'),clean=(v:unknown)=>typeof v==='string'?v.trim():''
const defaults:ContactSettings={heroKicker:'CONTACT AFGHAN POWER GROUP',heroTitle:'Start with the',heroHighlight:'right team.',heroText:'Education, travel, technology or media — tell us what you need and we’ll help you reach the right division without the back-and-forth.',phone:'+93 700 000 000',email:'info@afghanpower.com',whatsapp:'+93 700 000 000',office:'Kabul, Afghanistan',workingHours:'Sat – Thu · 8:30 AM – 5:00 PM',infoTitle:'Visit, call or message us.',infoText:'Reach Afghan Power Group directly for education, travel, technology and media inquiries.',mapTitle:'Visit us in Kabul.',mapText:'Use the map below to find our office.',mapEmbedUrl:'https://www.google.com/maps?q=Kabul%2C%20Afghanistan&output=embed',translations:{},divisions:[{id:'education',label:'EDUCATION',title:'Educational Consultancy',text:'Study visas, university admissions, scholarships and international education guidance.',visible:true,sortOrder:1,translations:{}},{id:'travel',label:'TRAVEL',title:'Travel Agency',text:'Tourist visas, air tickets, travel packages and practical journey support.',visible:true,sortOrder:2,translations:{}},{id:'technology',label:'TECHNOLOGY',title:'Tech Development',text:'Software, databases, ERP systems, websites and custom digital solutions.',visible:true,sortOrder:3,translations:{}},{id:'media',label:'MEDIA',title:'Media Production',text:'Advertising, video production, branding, design and digital marketing services.',visible:true,sortOrder:4,translations:{}}]}
function textTr(v:any){const o:Partial<ContactTextFields>={};for(const k of ['heroKicker','heroTitle','heroHighlight','heroText','office','workingHours','infoTitle','infoText','mapTitle','mapText'] as const){const x=clean(v?.[k]);if(x)(o as any)[k]=x}return o}
function divTr(v:any){const o:Partial<ContactDivisionText>={};for(const k of ['label','title','text'] as const){const x=clean(v?.[k]);if(x)(o as any)[k]=x}return o}
function normalize(input:Partial<ContactSettings>):ContactSettings{const divisions=Array.isArray(input.divisions)?input.divisions.map((d:any,i)=>({id:clean(d.id).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||`division-${i+1}`,label:clean(d.label),title:clean(d.title),text:clean(d.text),visible:d.visible!==false,sortOrder:Number.isFinite(Number(d.sortOrder))?Number(d.sortOrder):i+1,translations:{fa:divTr(d.translations?.fa),ps:divTr(d.translations?.ps)}})):defaults.divisions;const out:ContactSettings={heroKicker:clean(input.heroKicker)||defaults.heroKicker,heroTitle:clean(input.heroTitle)||defaults.heroTitle,heroHighlight:clean(input.heroHighlight)||defaults.heroHighlight,heroText:clean(input.heroText)||defaults.heroText,phone:clean(input.phone)||defaults.phone,email:clean(input.email)||defaults.email,whatsapp:clean(input.whatsapp)||defaults.whatsapp,office:clean(input.office)||defaults.office,workingHours:clean(input.workingHours)||defaults.workingHours,infoTitle:clean(input.infoTitle)||defaults.infoTitle,infoText:clean(input.infoText)||defaults.infoText,mapTitle:clean(input.mapTitle)||defaults.mapTitle,mapText:clean(input.mapText)||defaults.mapText,mapEmbedUrl:clean(input.mapEmbedUrl)||defaults.mapEmbedUrl,translations:{fa:textTr(input.translations?.fa),ps:textTr(input.translations?.ps)},divisions};if(!out.email.includes('@'))throw new Error('Enter a valid contact email.');return out}
async function read(file:string){try{return normalize(JSON.parse(await readFile(file,'utf8')))}catch(e:any){if(e?.code==='ENOENT')return defaults;throw e}}
async function write(file:string,d:ContactSettings){await mkdir(path.dirname(file),{recursive:true});const t=`${file}.tmp`;await writeFile(t,JSON.stringify(d,null,2)+'\n','utf8');await rename(t,file)}
export function createContactStore(file=defaultFile){return{async get(){const d=await read(file);return{...d,divisions:d.divisions.filter(x=>x.visible).sort((a,b)=>a.sortOrder-b.sortOrder)}},async getAdmin(){const d=await read(file);return{...d,divisions:[...d.divisions].sort((a,b)=>a.sortOrder-b.sortOrder)}},async update(input:Partial<ContactSettings>){const n=normalize(input);await write(file,n);return n}}}
const s=createContactStore();export const getContact=s.get;export const getAdminContact=s.getAdmin;export const updateContact=s.update
