import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
export const newsCategories=['education','travel','technology','media','company'] as const
export type NewsCategory=typeof newsCategories[number]
export type NewsTextFields={title:string;summary:string;readTime:string}
export type NewsInput=NewsTextFields&{id:string;category:NewsCategory;date:string;featured:boolean;visible:boolean;sortOrder:number;image:string;translations?:{fa?:Partial<NewsTextFields>;ps?:Partial<NewsTextFields>}}
export type NewsRecord=NewsInput&{createdAt:string;updatedAt:string}
const moduleDir=path.dirname(fileURLToPath(import.meta.url)),defaultDataFile=path.join(moduleDir,'data','news.json'),clean=(v:unknown)=>typeof v==='string'?v.trim():''
function tr(v:any){const o:Partial<NewsTextFields>={};for(const k of ['title','summary','readTime'] as const){const x=clean(v?.[k]);if(x)(o as any)[k]=x}return o}
function normalize(input:NewsInput):NewsInput{const id=clean(input.id).toLowerCase();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id))throw new Error('Enter a valid news id using lowercase letters, numbers and hyphens.');if(!newsCategories.includes(input.category))throw new Error('Choose a valid news category.');const title=clean(input.title),summary=clean(input.summary),image=clean(input.image),date=clean(input.date);if(!title)throw new Error('News title is required.');if(!summary)throw new Error('News summary is required.');if(!image)throw new Error('News image is required.');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Choose a valid news date.');return{id,title,category:input.category,date,readTime:clean(input.readTime)||'3 min read',featured:input.featured===true,visible:input.visible!==false,sortOrder:Number.isFinite(Number(input.sortOrder))?Number(input.sortOrder):0,image,summary,translations:{fa:tr(input.translations?.fa),ps:tr(input.translations?.ps)}}}
async function read(file:string):Promise<NewsRecord[]>{try{const a=JSON.parse(await readFile(file,'utf8'));if(!Array.isArray(a))return[];return a.map((x:any)=>({...normalize(x),createdAt:clean(x.createdAt)||new Date().toISOString(),updatedAt:clean(x.updatedAt)||new Date().toISOString()}))}catch(e:any){if(e?.code==='ENOENT')return[];throw e}}
async function write(file:string,a:NewsRecord[]){await mkdir(path.dirname(file),{recursive:true});const t=`${file}.tmp`;await writeFile(t,JSON.stringify(a,null,2)+'\n','utf8');await rename(t,file)}
export function createNewsStore(file=defaultDataFile){return{async listNews(o:{includeHidden?:boolean}={}){return(await read(file)).filter(x=>o.includeHidden||x.visible).sort((a,b)=>a.sortOrder-b.sortOrder||b.date.localeCompare(a.date)||a.title.localeCompare(b.title))},async getNews(id:string,o:{includeHidden?:boolean}={}){const x=(await read(file)).find(i=>i.id===id);return !x||(!o.includeHidden&&!x.visible)?null:x},async createNews(input:NewsInput){const n=normalize(input),a=await read(file);if(a.some(x=>x.id===n.id))throw new Error('A news item with this id already exists.');const now=new Date().toISOString(),x={...n,createdAt:now,updatedAt:now};a.push(x);await write(file,a);return x},async updateNews(id:string,input:NewsInput){const a=await read(file),i=a.findIndex(x=>x.id===id);if(i<0)return null;const n=normalize({...input,id}),x={...a[i],...n,id,createdAt:a[i].createdAt,updatedAt:new Date().toISOString()};a[i]=x;await write(file,a);return x},async deleteNews(id:string){const a=await read(file),n=a.filter(x=>x.id!==id);if(n.length===a.length)return false;await write(file,n);return true}}}
const s=createNewsStore();export const listNews=s.listNews;export const getNews=s.getNews;export const createNews=s.createNews;export const updateNews=s.updateNews;export const deleteNews=s.deleteNews
