import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
export const serviceCategories=['education','travel','technology','media'] as const
export type ServiceCategory=typeof serviceCategories[number]
export type ServiceTextFields={title:string;description:string;actionLabel:string}
export type ServiceInput=ServiceTextFields&{id:string;category:ServiceCategory;image:string;featured:boolean;visible:boolean;sortOrder:number;actionHref:string;translations?:{fa?:Partial<ServiceTextFields>;ps?:Partial<ServiceTextFields>}}
export type ServiceRecord=ServiceInput&{createdAt:string;updatedAt:string}
const moduleDir=path.dirname(fileURLToPath(import.meta.url)),defaultDataFile=path.join(moduleDir,'data','services.json'),clean=(v:unknown)=>typeof v==='string'?v.trim():''
function tr(v:any){const o:Partial<ServiceTextFields>={};for(const k of ['title','description','actionLabel'] as const){const x=clean(v?.[k]);if(x)(o as any)[k]=x}return o}
function normalize(input:ServiceInput):ServiceInput{const id=clean(input.id).toLowerCase();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id))throw new Error('Enter a valid service id using lowercase letters, numbers and hyphens.');if(!serviceCategories.includes(input.category))throw new Error('Choose a valid service category.');const title=clean(input.title),description=clean(input.description),image=clean(input.image);if(!title)throw new Error('Service title is required.');if(!description)throw new Error('Service description is required.');if(!image)throw new Error('Service image is required.');return{id,category:input.category,title,description,image,featured:input.featured===true,visible:input.visible!==false,sortOrder:Number.isFinite(Number(input.sortOrder))?Number(input.sortOrder):0,actionLabel:clean(input.actionLabel)||'Learn more',actionHref:clean(input.actionHref)||'#/contact',translations:{fa:tr(input.translations?.fa),ps:tr(input.translations?.ps)}}}
async function read(file:string):Promise<ServiceRecord[]>{try{const a=JSON.parse(await readFile(file,'utf8'));if(!Array.isArray(a))return[];return a.map((x:any)=>({...normalize(x),createdAt:clean(x.createdAt)||new Date().toISOString(),updatedAt:clean(x.updatedAt)||new Date().toISOString()}))}catch(e:any){if(e?.code==='ENOENT')return[];throw e}}
async function write(file:string,a:ServiceRecord[]){await mkdir(path.dirname(file),{recursive:true});const t=`${file}.tmp`;await writeFile(t,JSON.stringify(a,null,2)+'\n','utf8');await rename(t,file)}
export function createServiceStore(file=defaultDataFile){return{async listServices(o:{includeHidden?:boolean}={}){return(await read(file)).filter(x=>o.includeHidden||x.visible).sort((a,b)=>a.sortOrder-b.sortOrder||a.title.localeCompare(b.title))},async getService(id:string,o:{includeHidden?:boolean}={}){const x=(await read(file)).find(i=>i.id===id);return !x||(!o.includeHidden&&!x.visible)?null:x},async createService(input:ServiceInput){const n=normalize(input),a=await read(file);if(a.some(x=>x.id===n.id))throw new Error('A service with this id already exists.');const now=new Date().toISOString(),x={...n,createdAt:now,updatedAt:now};a.push(x);await write(file,a);return x},async updateService(id:string,input:ServiceInput){const a=await read(file),i=a.findIndex(x=>x.id===id);if(i<0)return null;const n=normalize({...input,id}),x={...a[i],...n,id,createdAt:a[i].createdAt,updatedAt:new Date().toISOString()};a[i]=x;await write(file,a);return x},async deleteService(id:string){const a=await read(file),n=a.filter(x=>x.id!==id);if(n.length===a.length)return false;await write(file,n);return true}}}
const s=createServiceStore();export const listServices=s.listServices;export const getService=s.getService;export const createService=s.createService;export const updateService=s.updateService;export const deleteService=s.deleteService
